### ISSUE TITLE
bro workers are very slow to stop on FreeBSD

### ISSUE THREAD

**Issue by klehigh** [sethhall/bro-myricom#3] opened 2018-04-19 18:39 UTC
Using FreeBSD 10.3 and the myricom plugin.  Myricom driver version : 3.0.12.50830 .  

When I attempt "broctl stop" I frequently have to try several times as workers do not stop on the first attempt (or even 2nd, or 3rd attempt).  The processes also don't respond to kill signals when I try to kill them directly.  I am using the default ring size.

**Comment by NoX1De** [comment] 2018-04-21 01:28
This doesn't sound like it's for certain a problem with the bro plugin for the myricom Sniffer drivers API?  Maybe send an email to the bro mailing list and see if you can get some help to narrow this down to be certain what the root of the issue is.  http://mailman.icsi.berkeley.edu/mailman/listinfo/bro

**Comment by klehigh** [comment] 2018-04-23 15:13
The problem goes away if I stop using this plugin, so it does seem to be directly related.

**Comment by sethhall** [comment] 2019-04-18 02:12
I don't believe that FreeBSD is a primary supported platform for Myricom anymore so I'm going to close this issue.

**Closed as completed by sethhall** 2019-04-18 02:12 UTC
